histogram
js-tasks-ru/htmlcss-20211021_fotex200 pull request #6
Opened 2021-11-02 00:24 UTC by apushkarou

2021-11-02 00:25 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-11-02 00:26 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-11-02 00:27 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-11-02 00:32 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-11-03 19:54 UTC, GSemikozov requested changes

2021-11-03 19:54 UTC, GSemikozov commented on 04-lection2/01-histogram/_histogram.scss
> +    height: 185px;
не будем жестко фиксировать высоту (у нас ведь текстовые элементы могут быть больше чем в 1 строку)

2021-11-03 19:54 UTC, GSemikozov commented on 04-lection2/01-histogram/_histogram.scss
> +            width: 50%;
вот здесь я бы тоже советовал на разделять четко пополам - все-таки справа лишь ссылка, а вот слева - может быть текста побольше

2021-11-03 19:54 UTC, GSemikozov commented on 04-lection2/01-histogram/_histogram.scss
> +            width: calc(3.33% - 1px);
это хорошо, если мы всегда знаем точное количество айтемов, но в нашем случае - я не зря сказал протестить кейс когда всего 1 или 2 колонки)
в общем, я бы советовал здесь использовать flex-basis: 9px

2021-11-03 19:54 UTC, GSemikozov commented on 04-lection2/01-histogram/_histogram.scss
> +            height: 100%;
и вот так конечно тоже категорически нельзя делать - вед если с сервера прилетит например null | undefined, а мы покажем дефолтное значение height 100% - это будет некорректно)

2021-11-04 01:48 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-11-04 01:49 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-11-04 01:52 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-11-04 01:57 UTC, apushkarou commented on 04-lection2/01-histogram/_histogram.scss
> +    height: 185px;
fixed

2021-11-04 02:03 UTC, apushkarou commented on 04-lection2/01-histogram/_histogram.scss
> +            width: calc(3.33% - 1px);
Тут конечно спорный вариант, хард кодить наверно не лучший вариант на фиксированное количество пиксилей, ибо тогда мы идем против responsive design, я бы наезжал на команду дизайнеров ) 

2 колнки
![image](https://user-images.githubusercontent.com/53324171/140245034-fa966501-5f75-4c25-b6cb-9895301f3311.png)

адаптиптив
![image](https://user-images.githubusercontent.com/53324171/140245126-b19bfa40-b248-4d62-a57c-3d08bc9108e6.png)

2021-11-04 02:05 UTC, apushkarou commented on 04-lection2/01-histogram/_histogram.scss
> +            height: 100%;
это да, не почистил тестовую разметку

2021-11-04 02:25 UTC, apushkarou commented on 04-lection2/01-histogram/_histogram.scss
> +            width: 50%;
исправлено

2021-11-04 19:45 UTC, GSemikozov commented on 04-lection2/01-histogram/_histogram.scss
> +            width: calc(3.33% - 1px);
так flex-basis это же просто базовая ширина, которая может как уменьшаться, так и увеличиваться в зависимости от совокупной ширины колонок))

2021-11-05 16:12 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-11-05 16:19 UTC, apushkarou commented on 04-lection2/01-histogram/_histogram.scss
> +            width: calc(3.33% - 1px);
Я что то явно упускаю, добавил flex-basis и адаптив сломан, наверно надо разобрать на занятии будет

2021-11-05 16:21 UTC, apushkarou commented on 04-lection2/01-histogram/_histogram.scss
> +            width: calc(3.33% - 1px);
Идея на сколько я понял захардкодить ширину колонки и сколько их будет помещаться - не наша проблема

2021-11-05 16:24 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-11-06 19:38 UTC, GSemikozov commented on 04-lection2/01-histogram/_histogram.scss
> +            width: calc(3.33% - 1px);
а если добавить flex-grow: 1?

2021-11-06 19:39 UTC, GSemikozov commented on 04-lection2/01-histogram/_histogram.scss
> +            width: calc(3.33% - 1px);
если меняем одни и те же файлы и стили в них в разных ПР-ах - конфликтов не избежать, их просто надо резолвить посредством актуализации ветки

2021-11-06 20:56 UTC, apushkarou commented on 04-lection2/01-histogram/_histogram.scss
> +            width: calc(3.33% - 1px);
спасибо, да с flex-basis и flex-grow решение элегантней - поправил

2021-11-07 12:11 UTC, GSemikozov approved these changes

2021-11-07 12:12 UTC, merged